steps:
  - name: 'docker'
    args: ['build', -t, 'gcr.io/test-hellotwin/trigger-task', '.']
  - name: 'docker'
    args: ['push', 'gcr.io/test-hellotwin/trigger-task']
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['run', 'deploy', 'trigger-task', '--image=gcr.io/test-hellotwin/trigger-task', '--platform=managed', '--region=global', 'allow-unauthenticated']
    
    timeout: 300s