apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-server
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      run: web-server
  template:
    metadata:
      labels:
        run: web-server
    spec:
      serviceAccountName: clean-cut-ksa
      nodeSelector:
        iam.gke.io/gke-metadata-server-enabled: "true"
      containers:
      - image: eu.gcr.io/test-hellotwin/web-image-043:634a84d
        imagePullPolicy: IfNotPresent
        name: web-server
        ports:
        - containerPort: 8080
          protocol: TCP