apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: clean-cut-ingress
  annotations:
    kubernetes.io/ingress.global-static-ip-name: "clean-cut-static-ip"
    kubernetes.io/ingress.class: "gce"
spec:
  rules:
    - http:
        paths:
          - path: /*
            pathType: ImplementationSpecific
            backend:
              service:
                name: clean-cut-service
                port: 
                  number: 8080
    - http:
        paths:
          - path: /*
            pathType: ImplementationSpecific
            backend:
              service:
                name: clean-cut-service
                port: 
                  number: 443