apiVersion: v1
kind: Service
metadata:
  name: node-port-test
  namespace: default
  annotations:
    beta.cloud.google.com/backend-config: '{"default": "backend-config"}'
spec:
  type: NodePort
  selector:
    run: iap-app-test
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
