apiVersion: v1
kind: Service
metadata:
  name: test-service
  namespace: default
  annotations:
    beta.cloud.google.com/backend-config: '{"default": "config-default"}'
spec:
  type: NodePort
  selector:
    run: another-test-web-server
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
